//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public string CPFAluno { get; set; }
        public string NomeAluno { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string NomeMae { get; set; }
        public string Endereco { get; set; }
    }
}
